server:
  port: 8020
spring:
  application:
    name: spring-config
  cloud:
    zookeeper:
      connect-string: 123.206.64.103
      discovery:
        enabled: true
        root: /admin-service
    config:
      label: master  # git仓库分支
      server:
        git:
          uri: https://github.com/Jerry201701/springcloud-demo.git  # 配置git仓库的地址
          search-paths: config-repo  # git仓库地址下的相对地址，可以配置多个，用,分割。
#          username: username  # git仓库的账号
#          password: password  # git仓库的密码
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: "*"